// Site-wide data for the Smiler clone

export const languages = [
  { code: "en", label: "English", flag: "GB" },
  { code: "de", label: "Deutsch", flag: "DE" },
  { code: "es", label: "Espanol", flag: "ES" },
  { code: "fr", label: "Francais", flag: "FR" },
  { code: "it", label: "Italiano", flag: "IT" },
  { code: "nl", label: "Nederlands", flag: "NL" },
] as const;

export const currencies = ["EUR", "USD", "GBP", "AUD", "CAD"] as const;

export type CitySlug = "paris" | "new-york" | "rome" | "barcelona" | "sydney";

export interface PhotoShoot {
  id: string;
  city: string;
  citySlug: CitySlug;
  title: string;
  image: string;
  imageCount: number;
  rating: number;
  reviewCount: number;
  price: number;
}

export interface CityInfo {
  name: string;
  slug: CitySlug;
  image: string;
  stickerId: string;
}

export const popularCities: CityInfo[] = [
  { name: "Paris", slug: "paris", image: "/images/paris.jpg", stickerId: "2988507" },
  { name: "New York City", slug: "new-york", image: "/images/new-york.jpg", stickerId: "5128581" },
  { name: "Rome", slug: "rome", image: "/images/rome.jpg", stickerId: "3169070" },
  { name: "Barcelona", slug: "barcelona", image: "/images/barcelona.jpg", stickerId: "3128760" },
  { name: "Sydney", slug: "sydney", image: "/images/sydney.jpg", stickerId: "2147714" },
];

export const photoShootsByCity: Record<CitySlug, PhotoShoot[]> = {
  paris: [
    { id: "p1", city: "Paris", citySlug: "paris", title: "Eiffel Tower shoot by top Paris photographer", image: "/images/shoots/paris-eiffel.jpg", imageCount: 6, rating: 4.9, reviewCount: 312, price: 89 },
    { id: "p2", city: "Paris", citySlug: "paris", title: "Montmartre & Sacre-Coeur photoshoot", image: "/images/shoots/paris-benoit.jpg", imageCount: 6, rating: 5.0, reviewCount: 187, price: 99 },
    { id: "p3", city: "Paris", citySlug: "paris", title: "Seine River & Notre Dame photo walk", image: "/images/shoots/paris-danni.jpg", imageCount: 6, rating: 4.8, reviewCount: 245, price: 79 },
    { id: "p4", city: "Paris", citySlug: "paris", title: "Louvre & Tuileries Garden session", image: "/images/shoots/paris-renato.jpg", imageCount: 6, rating: 4.9, reviewCount: 198, price: 109 },
  ],
  "new-york": [
    { id: "ny1", city: "New York City", citySlug: "new-york", title: "Times Square photoshoot by top New York photographer", image: "/images/shoots/nyc-hanna.jpg", imageCount: 6, rating: 4.9, reviewCount: 276, price: 330 },
    { id: "ny2", city: "New York City", citySlug: "new-york", title: "Central Park Family Photoshoot", image: "/images/shoots/nyc-moselle.jpg", imageCount: 5, rating: 4.9, reviewCount: 203, price: 300 },
    { id: "ny3", city: "New York City", citySlug: "new-york", title: "Dumbo (Manhattan Bridge)", image: "/images/shoots/nyc-anton.jpg", imageCount: 6, rating: 5.0, reviewCount: 158, price: 340 },
    { id: "ny4", city: "New York City", citySlug: "new-york", title: "Bridges of New York Photo Tour", image: "/images/shoots/nyc-dariia.jpg", imageCount: 6, rating: 4.6, reviewCount: 142, price: 300 },
  ],
  rome: [
    { id: "r1", city: "Rome", citySlug: "rome", title: "Colosseum & Roman Forum photoshoot", image: "/images/shoots/rome-camtu.jpg", imageCount: 6, rating: 4.9, reviewCount: 289, price: 79 },
    { id: "r2", city: "Rome", citySlug: "rome", title: "Trevi Fountain & Spanish Steps session", image: "/images/shoots/rome-valentina.jpg", imageCount: 6, rating: 5.0, reviewCount: 341, price: 89 },
    { id: "r3", city: "Rome", citySlug: "rome", title: "Vatican & St. Peter's Square shoot", image: "/images/shoots/rome-samira.jpg", imageCount: 6, rating: 4.8, reviewCount: 167, price: 99 },
    { id: "r4", city: "Rome", citySlug: "rome", title: "Trastevere evening photo walk", image: "/images/shoots/rome-mahan.jpg", imageCount: 5, rating: 4.9, reviewCount: 213, price: 69 },
  ],
  barcelona: [
    { id: "b1", city: "Barcelona", citySlug: "barcelona", title: "Sagrada Familia shoot by top Barcelona photographer", image: "/images/shoots/barcelona-sagrada.jpg", imageCount: 6, rating: 5.0, reviewCount: 298, price: 89 },
    { id: "b2", city: "Barcelona", citySlug: "barcelona", title: "Park Guell panoramic photo session", image: "/images/shoots/barcelona-guell.jpg", imageCount: 6, rating: 4.8, reviewCount: 176, price: 79 },
    { id: "b3", city: "Barcelona", citySlug: "barcelona", title: "La Barceloneta Beach sunset shoot", image: "/images/shoots/barcelona-beach.jpg", imageCount: 6, rating: 4.9, reviewCount: 234, price: 69 },
    { id: "b4", city: "Barcelona", citySlug: "barcelona", title: "Gothic Quarter & Las Ramblas walk", image: "/images/shoots/barcelona-arc.jpg", imageCount: 6, rating: 4.7, reviewCount: 189, price: 79 },
  ],
  sydney: [
    { id: "s1", city: "Sydney", citySlug: "sydney", title: "Opera House & Harbour Bridge shoot", image: "/images/shoots/sydney-maria.jpg", imageCount: 5, rating: 4.9, reviewCount: 245, price: 99 },
    { id: "s2", city: "Sydney", citySlug: "sydney", title: "Bondi Beach lifestyle photoshoot", image: "/images/shoots/sydney-jack.jpg", imageCount: 6, rating: 4.8, reviewCount: 178, price: 89 },
    { id: "s3", city: "Sydney", citySlug: "sydney", title: "Royal Botanic Garden session", image: "/images/shoots/sydney-jose.jpg", imageCount: 6, rating: 5.0, reviewCount: 134, price: 79 },
    { id: "s4", city: "Sydney", citySlug: "sydney", title: "Circular Quay sunset portraits", image: "/images/shoots/sydney-amy.jpg", imageCount: 6, rating: 4.9, reviewCount: 201, price: 109 },
  ],
};

export const browseLandmarks: { name: string; image: string; stickerId: string }[] = [
  { name: "Paris", image: "/images/paris.jpg", stickerId: "2988507" },
  { name: "New York City", image: "/images/new-york.jpg", stickerId: "5128581" },
  { name: "Rome", image: "/images/rome.jpg", stickerId: "3169070" },
  { name: "Barcelona", image: "/images/barcelona.jpg", stickerId: "3128760" },
  { name: "Dubai", image: "/images/dubai.jpg", stickerId: "292223" },
];

export const cityTripShoots: PhotoShoot[] = [
  { id: "ct1", city: "Santorini", citySlug: "paris", title: "Oia Village shoot by Santorini photographer", image: "/images/shoots/london-mehr.jpg", imageCount: 6, rating: 4.9, reviewCount: 198, price: 129 },
  { id: "ct2", city: "Miami", citySlug: "new-york", title: "Miami Beach", image: "/images/shoots/dubai-recep.jpg", imageCount: 6, rating: 5.0, reviewCount: 312, price: 300 },
  { id: "ct3", city: "Venice", citySlug: "rome", title: "Piazza San Marco shoot by Venice photographer", image: "/images/shoots/rome-valentina.jpg", imageCount: 6, rating: 4.9, reviewCount: 156, price: 89 },
  { id: "ct4", city: "Washington, DC", citySlug: "new-york", title: "Romantic photoshoot for couples", image: "/images/shoots/nyc-dariia.jpg", imageCount: 6, rating: 4.9, reviewCount: 267, price: 330 },
  { id: "ct5", city: "Rome", citySlug: "rome", title: "Flying dress photoshoot at Colosseum in Rome", image: "/images/shoots/rome-aras.jpg", imageCount: 6, rating: 4.9, reviewCount: 89, price: 310 },
  { id: "ct6", city: "Como", citySlug: "rome", title: "Private photo tour around Como", image: "/images/shoots/lanzarote-laura.jpg", imageCount: 6, rating: 5.0, reviewCount: 178, price: 210 },
];

// Translations
export const translations: Record<string, Record<string, string>> = {
  en: {
    "nav.photographers": "Photographers",
    "nav.partners": "Partners",
    "hero.title": "Capturing moments you'll never forget",
    "hero.subtitle": "Book your next photoshoot experience. Available in 150+ locations",
    "hero.cta": "See all cities",
    "popular.title": "Popular photo spots",
    "browse.title": "Browse other iconic landmarks",
    "browse.cta": "See all photoshoots",
    "citytrip.title": "Book a photoshoot for your next city trip",
    "citytrip.cta": "See all photoshoots",
    "stats.locations": "150+ locations",
    "stats.photoshoots": "10,000+ photoshoots",
    "stats.rating": "4.9 average rating",
    "howit.title": "How it works",
    "howit.step1.title": "Choose your shoot",
    "howit.step1.desc": "Browse photoshoots in 150+ cities worldwide and find your perfect match",
    "howit.step2.title": "Book instantly",
    "howit.step2.desc": "Pick your date, time, and location. Confirm your booking in seconds",
    "howit.step3.title": "Receive your photos",
    "howit.step3.desc": "Get your professionally edited photos delivered within 48 hours",
    "footer.explore": "Explore",
    "footer.support": "Support",
    "footer.company": "Company",
    "footer.workwithus": "Work with us",
    "footer.contact": "Contact",
    "footer.privacy": "Privacy policy",
    "footer.cookies": "Cookies",
    "footer.terms": "Terms of use",
    "footer.about": "About us",
    "footer.careers": "Careers",
    "footer.become_photographer": "Become a Photographer",
    "footer.photographer_portal": "Photographer Portal Login",
    "footer.become_partner": "Become a Partner",
    "footer.tagline": "Capturing moments that matter",
    "footer.copyright": "Smiler",
    "currency.select": "Select currency",
    "language.select": "Select language",
  },
  de: {
    "nav.photographers": "Fotografen",
    "nav.partners": "Partner",
    "hero.title": "Momente festhalten, die du nie vergisst",
    "hero.subtitle": "Buche dein nachstes Fotoshooting-Erlebnis. Verfugbar an 150+ Standorten",
    "hero.cta": "Alle Stadte anzeigen",
    "popular.title": "Beliebte Fotospots",
    "browse.title": "Weitere ikonische Wahrzeichen entdecken",
    "browse.cta": "Alle Fotoshootings anzeigen",
    "citytrip.title": "Buche ein Fotoshooting fur deinen nachsten Stadtetrip",
    "citytrip.cta": "Alle Fotoshootings anzeigen",
    "stats.locations": "150+ Standorte",
    "stats.photoshoots": "10.000+ Fotoshootings",
    "stats.rating": "4.9 Durchschnittsbewertung",
    "howit.title": "So funktioniert es",
    "howit.step1.title": "Wahle dein Shooting",
    "howit.step1.desc": "Durchsuche Fotoshootings in 150+ Stadten weltweit",
    "howit.step2.title": "Sofort buchen",
    "howit.step2.desc": "Wahle Datum, Uhrzeit und Ort. Bestatige in Sekunden",
    "howit.step3.title": "Erhalte deine Fotos",
    "howit.step3.desc": "Professionell bearbeitete Fotos innerhalb von 48 Stunden",
    "footer.explore": "Entdecken",
    "footer.support": "Hilfe",
    "footer.company": "Unternehmen",
    "footer.workwithus": "Arbeite mit uns",
    "footer.contact": "Kontakt",
    "footer.privacy": "Datenschutz",
    "footer.cookies": "Cookies",
    "footer.terms": "Nutzungsbedingungen",
    "footer.about": "Uber uns",
    "footer.careers": "Karriere",
    "footer.become_photographer": "Fotograf werden",
    "footer.photographer_portal": "Fotografen-Portal Login",
    "footer.become_partner": "Partner werden",
    "footer.tagline": "Momente festhalten, die zahlen",
    "footer.copyright": "Smiler",
    "currency.select": "Wahrung wahlen",
    "language.select": "Sprache wahlen",
  },
  es: {
    "nav.photographers": "Fotografos",
    "nav.partners": "Socios",
    "hero.title": "Capturando momentos que nunca olvidaras",
    "hero.subtitle": "Reserva tu proxima sesion de fotos. Disponible en mas de 150 ubicaciones",
    "hero.cta": "Ver todas las ciudades",
    "popular.title": "Lugares fotograficos populares",
    "browse.title": "Explora otros lugares iconicos",
    "browse.cta": "Ver todas las sesiones",
    "citytrip.title": "Reserva una sesion de fotos para tu proximo viaje",
    "citytrip.cta": "Ver todas las sesiones",
    "stats.locations": "150+ ubicaciones",
    "stats.photoshoots": "10.000+ sesiones de fotos",
    "stats.rating": "4.9 calificacion promedio",
    "howit.title": "Como funciona",
    "howit.step1.title": "Elige tu sesion",
    "howit.step1.desc": "Explora sesiones en 150+ ciudades del mundo",
    "howit.step2.title": "Reserva al instante",
    "howit.step2.desc": "Selecciona fecha, hora y lugar. Confirma en segundos",
    "howit.step3.title": "Recibe tus fotos",
    "howit.step3.desc": "Fotos profesionales editadas en 48 horas",
    "footer.explore": "Explorar",
    "footer.support": "Soporte",
    "footer.company": "Empresa",
    "footer.workwithus": "Trabaja con nosotros",
    "footer.contact": "Contacto",
    "footer.privacy": "Politica de privacidad",
    "footer.cookies": "Cookies",
    "footer.terms": "Condiciones de uso",
    "footer.about": "Sobre nosotros",
    "footer.careers": "Carreras",
    "footer.become_photographer": "Ser Fotografo",
    "footer.photographer_portal": "Portal del Fotografo",
    "footer.become_partner": "Ser Socio",
    "footer.tagline": "Capturando momentos que importan",
    "footer.copyright": "Smiler",
    "currency.select": "Seleccionar moneda",
    "language.select": "Seleccionar idioma",
  },
  fr: {
    "nav.photographers": "Photographes",
    "nav.partners": "Partenaires",
    "hero.title": "Capturer des moments inoubliables",
    "hero.subtitle": "Reservez votre prochaine seance photo. Disponible dans plus de 150 lieux",
    "hero.cta": "Voir toutes les villes",
    "popular.title": "Spots photo populaires",
    "browse.title": "Decouvrez d'autres lieux emblematiques",
    "browse.cta": "Voir toutes les seances",
    "citytrip.title": "Reservez un shooting pour votre prochain voyage",
    "citytrip.cta": "Voir toutes les seances",
    "stats.locations": "150+ lieux",
    "stats.photoshoots": "10 000+ seances photo",
    "stats.rating": "4.9 note moyenne",
    "howit.title": "Comment ca marche",
    "howit.step1.title": "Choisissez votre seance",
    "howit.step1.desc": "Parcourez les seances photo dans plus de 150 villes",
    "howit.step2.title": "Reservez instantanement",
    "howit.step2.desc": "Choisissez la date, l'heure et le lieu. Confirmez en quelques secondes",
    "howit.step3.title": "Recevez vos photos",
    "howit.step3.desc": "Photos professionnelles editees en 48 heures",
    "footer.explore": "Explorer",
    "footer.support": "Support",
    "footer.company": "Entreprise",
    "footer.workwithus": "Travaillez avec nous",
    "footer.contact": "Contact",
    "footer.privacy": "Politique de confidentialite",
    "footer.cookies": "Cookies",
    "footer.terms": "Conditions d'utilisation",
    "footer.about": "A propos",
    "footer.careers": "Carrieres",
    "footer.become_photographer": "Devenir Photographe",
    "footer.photographer_portal": "Portail Photographe",
    "footer.become_partner": "Devenir Partenaire",
    "footer.tagline": "Capturer les moments qui comptent",
    "footer.copyright": "Smiler",
    "currency.select": "Selectionner la devise",
    "language.select": "Selectionner la langue",
  },
  it: {
    "nav.photographers": "Fotografi",
    "nav.partners": "Partner",
    "hero.title": "Cattura momenti indimenticabili",
    "hero.subtitle": "Prenota la tua prossima esperienza fotografica. Disponibile in oltre 150 localita",
    "hero.cta": "Vedi tutte le citta",
    "popular.title": "Luoghi fotografici popolari",
    "browse.title": "Esplora altri luoghi iconici",
    "browse.cta": "Vedi tutti i servizi fotografici",
    "citytrip.title": "Prenota un servizio fotografico per il tuo prossimo viaggio",
    "citytrip.cta": "Vedi tutti i servizi fotografici",
    "stats.locations": "150+ localita",
    "stats.photoshoots": "10.000+ servizi fotografici",
    "stats.rating": "4.9 valutazione media",
    "footer.explore": "Esplora",
    "footer.support": "Supporto",
    "footer.company": "Azienda",
    "footer.workwithus": "Lavora con noi",
    "footer.tagline": "Catturare i momenti che contano",
    "footer.copyright": "Smiler",
    "currency.select": "Seleziona valuta",
    "language.select": "Seleziona lingua",
  },
  nl: {
    "nav.photographers": "Fotografen",
    "nav.partners": "Partners",
    "hero.title": "Momenten vastleggen die je nooit vergeet",
    "hero.subtitle": "Boek je volgende fotoshoot ervaring. Beschikbaar op 150+ locaties",
    "hero.cta": "Bekijk alle steden",
    "popular.title": "Populaire fotolocaties",
    "browse.title": "Ontdek andere iconische bezienswaardigheden",
    "browse.cta": "Bekijk alle fotoshoots",
    "citytrip.title": "Boek een fotoshoot voor je volgende stedentrip",
    "citytrip.cta": "Bekijk alle fotoshoots",
    "stats.locations": "150+ locaties",
    "stats.photoshoots": "10.000+ fotoshoots",
    "stats.rating": "4.9 gemiddelde beoordeling",
    "footer.explore": "Ontdekken",
    "footer.support": "Ondersteuning",
    "footer.company": "Bedrijf",
    "footer.workwithus": "Werk met ons",
    "footer.tagline": "Momenten vastleggen die ertoe doen",
    "footer.copyright": "Smiler",
    "currency.select": "Selecteer valuta",
    "language.select": "Selecteer taal",
  },
};
